In [4]:
import numpy as np

In [5]:
import pandas as pd

### 1.	Create a 2D array and print the dim and shape

In [7]:
a = np.array([[1, 6, 3, 9], [8, 5, 5, 3]])
a.ndim

2

In [8]:
a.shape

(2, 4)

### 2.	Create an array of 20 numbers using arange function and slice the values between 10 to 15

In [20]:
b = np.arange(20)
b[slice(11, 15)]

array([11, 12, 13, 14])

### 3.	Create 2 arrays of 7X5 dimension and broadcast between the 2 arrays using 
a.	Addition
b.	Subtraction
c.	Multiplication
d.	Division


In [22]:
arr1 = np.array([[[[[[[4, 3, 8, 1, 2], [10, 7, 8, 4, 2], [2, 1, 7, 8, 6], [3, 5, 5, 6, 1], [1, 3, 3, 3, 8], [1, 9, 9, 9, 2], [22, 9, 10, 22, 2]]]]]]])
arr2 = np.array([[[[[[[3, 3, 8, 11, 2], [1, 7, 8, 2, 2], [2, 8, 1, 8, 6], [3, 4, 3, 1, 1], [1, 3, 8, 3, 8], [1, 5, 9, 2, 22], [2, 9, 10, 2, 21]]]]]]])
add = np.add(arr1, arr2)
sub = np.subtract(arr1, arr2)
multiple = np.multiply(arr1, arr2)
divide = np.divide(arr1, arr2)
print(add)
print(sub)
print(multiple)
print(divide)


[[[[[[[ 7  6 16 12  4]
      [11 14 16  6  4]
      [ 4  9  8 16 12]
      [ 6  9  8  7  2]
      [ 2  6 11  6 16]
      [ 2 14 18 11 24]
      [24 18 20 24 23]]]]]]]
[[[[[[[  1   0   0 -10   0]
      [  9   0   0   2   0]
      [  0  -7   6   0   0]
      [  0   1   2   5   0]
      [  0   0  -5   0   0]
      [  0   4   0   7 -20]
      [ 20   0   0  20 -19]]]]]]]
[[[[[[[ 12   9  64  11   4]
      [ 10  49  64   8   4]
      [  4   8   7  64  36]
      [  9  20  15   6   1]
      [  1   9  24   9  64]
      [  1  45  81  18  44]
      [ 44  81 100  44  42]]]]]]]
[[[[[[[ 1.33333333  1.          1.          0.09090909  1.        ]
      [10.          1.          1.          2.          1.        ]
      [ 1.          0.125       7.          1.          1.        ]
      [ 1.          1.25        1.66666667  6.          1.        ]
      [ 1.          1.          0.375       1.          1.        ]
      [ 1.          1.8         1.          4.5         0.09090909]
      [11.          1

### 4.	Create 2 incompatible arrays for broadcast and print out the error

In [26]:
arr3 = ([[2, 1, 3, 4], [7, 8, 9, 10]])
arr4 = ([[1, 2, 0],[2, 3, 4]])
addition = np.add(arr3, arr4)
print(addition)

#Error: operands could not be broadcast together with shapes (2,4) (2,3) 


ValueError: operands could not be broadcast together with shapes (2,4) (2,3) 

### 5.	Create two arrays of any dimension and perform vstack and hstack

In [39]:
array1 = np.array([[22, 65, 90, 19], [23, 32, 42, 52]])
array2 = np.array([[1, 12, 15, 46], [98, 48, 23, 56]])
hstack = np.stack((array1, array2), axis = 0)
vstack = np.stack((array1, array2), axis = 1)
print(hstack)
print(vstack)

[[[22 65 90 19]
  [23 32 42 52]]

 [[ 1 12 15 46]
  [98 48 23 56]]]
[[[22 65 90 19]
  [ 1 12 15 46]]

 [[23 32 42 52]
  [98 48 23 56]]]


### 6.	Append two arrays using axis = 0 and axis = 1

In [45]:
array1 = np.array([[22, 65, 90, 19], [23, 32, 42, 52]])
array2 = np.array([[1, 12, 15, 46], [98, 48, 23, 56]])
app = np.append(list1, list2, axis = 0)
print(app)

[[22 65 90 19]
 [23 32 42 52]
 [ 1 12 15 46]
 [98 48 23 56]]


In [46]:
app1 = np.append(list1, list2, axis = 1)
app1

array([[22, 65, 90, 19,  1, 12, 15, 46],
       [23, 32, 42, 52, 98, 48, 23, 56]])

### 7.	Create a dataframe for 8 X 4 dimension using list of lists and name the columns while dataframe creation

In [52]:
list1 = [['Prasanth', 21, 'ECE', 2022], ['Saran', 21, 'ECE', 2022], ['Kiritik raja', 21, 'ECE', 2022], ['Dhanush', 21, 'EEE', 2022], ['Dhanunjay', 21, 'ECE', 2022], ['Subash', 21, 'ECE', 2022], ['Dhuren', 24, 'ECE', 2019], ['Harish', 21, 'ECE', 2022]]
df = pd.DataFrame(list1, columns = ('Name', 'Age', 'Stream', 'Passed out'))
df

Name  Age Stream  Passed out
0      Prasanth   21    ECE        2022
1         Saran   21    ECE        2022
2  Kiritik raja   21    ECE        2022
3       Dhanush   21    EEE        2022
4     Dhanunjay   21    ECE        2022
5        Subash   21    ECE        2022
6        Dhuren   24    ECE        2019
7        Harish   21    ECE        2022

### 8.	Create a dataframe of 4 X 8 dimension using a dictionary

In [54]:
dictionary = {'State': ['Tamilnadu', 'Madhya Pradesh', 'Chattisgarh', 'Jammu'], 'Players': ['Siva', 'Uchit', 'Arun', 'Ajay'], 'Age': [18, 26, 30, 22], 'Medal': ['Bronze', 'Gold', 'Gold', 'Siver'], 'Weight': [56, 52, 65, 70], 'Height': [5, 5.5, 6, 5.4], 'Experience': ['Junior', 'Senior', 'Senior', 'Junior'], 'International Player': ['No', 'Yes', 'Yes', 'No']}
df1 = pd.DataFrame(dictionary)
df1

State Players  Age   Medal  Weight  Height Experience  \
0       Tamilnadu    Siva   18  Bronze      56     5.0     Junior   
1  Madhya Pradesh   Uchit   26    Gold      52     5.5     Senior   
2     Chattisgarh    Arun   30    Gold      65     6.0     Senior   
3           Jammu    Ajay   22   Siver      70     5.4     Junior   

  International Player  
0                   No  
1                  Yes  
2                  Yes  
3                   No

### 9.	Use loc and iloc to subset the data for the above dataframe

In [66]:
df1.loc[0:3, ['Players', 'Medal']]

Players   Medal
0    Siva  Bronze
1   Uchit    Gold
2    Arun    Gold
3    Ajay   Siver

In [59]:
df1.iloc[0:3, 1:4]

Players  Age   Medal
0    Siva   18  Bronze
1   Uchit   26    Gold
2    Arun   30    Gold

### 10.	How to check the total number of not null values in a column?

In [12]:
df2 = pd.DataFrame({'Name': ['Jagan', 'Rohit', 'Keshav', 'John'], 'Age': [30, 23, 14, 18], 'Score': [88, 99, 76, 92], 'Rating': ['A', 'S', 'B', 'A']}, index = ['a', 'c', 'e', 'f'])
df2

Name  Age  Score Rating
a   Jagan   30     88      A
c   Rohit   23     99      S
e  Keshav   14     76      B
f    John   18     92      A

In [18]:
df3 = df2.reindex(['a', 'b', 'c', 'd', 'e', 'f', 'g'])
df3

Name   Age  Score Rating
a   Jagan  30.0   88.0      A
b     NaN   NaN    NaN    NaN
c   Rohit  23.0   99.0      S
d     NaN   NaN    NaN    NaN
e  Keshav  14.0   76.0      B
f    John  18.0   92.0      A
g     NaN   NaN    NaN    NaN

In [22]:
df3['Rating'].notnull()

a     True
b    False
c     True
d    False
e     True
f     True
g    False
Name: Rating, dtype: bool

### 11.	Create a dataframe with missing values and fill them all with 100

In [25]:
df = pd.DataFrame({'Name': ['Jagan', 'Rohit', 'Keshav', 'John'], 'Age': [30, 23, 14, 18], 'Score': [88, 99, 76, 92], 'Rating': ['A', 'S', 'B', 'A']}, index = ['a', 'c', 'e', 'f'])
df

Name  Age  Score Rating
a   Jagan   30     88      A
c   Rohit   23     99      S
e  Keshav   14     76      B
f    John   18     92      A

In [28]:
df4= df2.reindex(['a', 'b', 'c', 'd', 'e', 'f', 'g'])
df4

Name   Age  Score Rating
a   Jagan  30.0   88.0      A
b     NaN   NaN    NaN    NaN
c   Rohit  23.0   99.0      S
d     NaN   NaN    NaN    NaN
e  Keshav  14.0   76.0      B
f    John  18.0   92.0      A
g     NaN   NaN    NaN    NaN

In [31]:
df5 = df4.fillna(100)
df5

Name    Age  Score Rating
a   Jagan   30.0   88.0      A
b     100  100.0  100.0    100
c   Rohit   23.0   99.0      S
d     100  100.0  100.0    100
e  Keshav   14.0   76.0      B
f    John   18.0   92.0      A
g     100  100.0  100.0    100

### 12.	Create a dataframe with missing values and drop the null records

In [32]:
df4

Name   Age  Score Rating
a   Jagan  30.0   88.0      A
b     NaN   NaN    NaN    NaN
c   Rohit  23.0   99.0      S
d     NaN   NaN    NaN    NaN
e  Keshav  14.0   76.0      B
f    John  18.0   92.0      A
g     NaN   NaN    NaN    NaN

In [33]:
df4.dropna()

Name   Age  Score Rating
a   Jagan  30.0   88.0      A
c   Rohit  23.0   99.0      S
e  Keshav  14.0   76.0      B
f    John  18.0   92.0      A

### 13.	Perform following aggregation task on below table
##### a.	Get the average age group by Region
##### b.	Get the sum of Age and Validation group by Hair color and then reset the index
##### c.	Get the mean and the median of Age group by Region


In [6]:
list1 = pd.DataFrame({'Age': [25, 30, 45, 35, 33, 35, 25, 52, 21, 24, 48, 22, 27, 28, 21, 51, 23], 
                     'Hair Color': ['Black', 'Black', 'Red', 'Blond', 'Brown', 'Brown', 'Black', 'Brown', 'Blond', 'Blond', 'Black', 'Black', 'Brown', 'Black', 'Blond', 'Black', 'Brown'], 
                     'US Region': ['Southwest', 'Northwest', 'Northeast', 'Southwest', 'Southwest', 'Northeast', 'Southwest', 'Southeast', 'Southwest', 'Northeast', 'Southwest', 'Southwest', 'Northeast', 'Southeast', 'Southeast', 'Northwest', 'Southeast'], 
                     'Validation': [1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1]})
list1

Age Hair Color  US Region  Validation
0    25      Black  Southwest           1
1    30      Black  Northwest           1
2    45        Red  Northeast           1
3    35      Blond  Southwest           0
4    33      Brown  Southwest           0
5    35      Brown  Northeast           0
6    25      Black  Southwest           0
7    52      Brown  Southeast           0
8    21      Blond  Southwest           1
9    24      Blond  Northeast           0
10   48      Black  Southwest           1
11   22      Black  Southwest           0
12   27      Brown  Northeast           0
13   28      Black  Southeast           1
14   21      Blond  Southeast           1
15   51      Black  Northwest           0
16   23      Brown  Southeast           1

In [7]:
# a)
list1.groupby(['US Region'])['Age'].mean()

US Region
Northeast    32.750000
Northwest    40.500000
Southeast    31.000000
Southwest    29.857143
Name: Age, dtype: float64

In [17]:
# b)
a = list1.groupby(['Hair Color'])['Age'].sum().reset_index()
b = list1.groupby(['Hair Color'])['Validation'].sum().reset_index()
print(a)
print(b)

  Hair Color  Age
0      Black  229
1      Blond  101
2      Brown  170
3        Red   45
  Hair Color  Validation
0      Black           4
1      Blond           2
2      Brown           1
3        Red           1


In [19]:
# c)
list1.groupby(['US Region'])['Age'].median()

US Region
Northeast    31.0
Northwest    40.5
Southeast    25.5
Southwest    25.0
Name: Age, dtype: float64

In [20]:
list1.groupby(['US Region'])['Age'].mean()

US Region
Northeast    32.750000
Northwest    40.500000
Southeast    31.000000
Southwest    29.857143
Name: Age, dtype: float64

### 14.	Split the below table into half and perform merge (inner, left and right) on Region. One example for each type of merge (inner, left and right)

In [21]:
list1

Age Hair Color  US Region  Validation
0    25      Black  Southwest           1
1    30      Black  Northwest           1
2    45        Red  Northeast           1
3    35      Blond  Southwest           0
4    33      Brown  Southwest           0
5    35      Brown  Northeast           0
6    25      Black  Southwest           0
7    52      Brown  Southeast           0
8    21      Blond  Southwest           1
9    24      Blond  Northeast           0
10   48      Black  Southwest           1
11   22      Black  Southwest           0
12   27      Brown  Northeast           0
13   28      Black  Southeast           1
14   21      Blond  Southeast           1
15   51      Black  Northwest           0
16   23      Brown  Southeast           1

In [24]:
df = list1[:8]
df

Age Hair Color  US Region  Validation
0   25      Black  Southwest           1
1   30      Black  Northwest           1
2   45        Red  Northeast           1
3   35      Blond  Southwest           0
4   33      Brown  Southwest           0
5   35      Brown  Northeast           0
6   25      Black  Southwest           0
7   52      Brown  Southeast           0

In [26]:
df1 = list1[8:]
df1

Age Hair Color  US Region  Validation
8    21      Blond  Southwest           1
9    24      Blond  Northeast           0
10   48      Black  Southwest           1
11   22      Black  Southwest           0
12   27      Brown  Northeast           0
13   28      Black  Southeast           1
14   21      Blond  Southeast           1
15   51      Black  Northwest           0
16   23      Brown  Southeast           1

In [33]:
# Inner merge

Inner_merge = df.merge(df1, on = 'US Region', how = 'inner')
Inner_merge

Age_x Hair Color_x  US Region  Validation_x  Age_y Hair Color_y  \
0      25        Black  Southwest             1     21        Blond   
1      25        Black  Southwest             1     48        Black   
2      25        Black  Southwest             1     22        Black   
3      35        Blond  Southwest             0     21        Blond   
4      35        Blond  Southwest             0     48        Black   
5      35        Blond  Southwest             0     22        Black   
6      33        Brown  Southwest             0     21        Blond   
7      33        Brown  Southwest             0     48        Black   
8      33        Brown  Southwest             0     22        Black   
9      25        Black  Southwest             0     21        Blond   
10     25        Black  Southwest             0     48        Black   
11     25        Black  Southwest             0     22        Black   
12     30        Black  Northwest             1     51        Black   
13     45          Red  Northeast             1     24        Blond   
14     45          Red  Northeast             1     27        Brown   
15     35        Brown  Northeast             0     24        Blond   
16     35        Brown  Northeast             0     27        Brown   
17     52        Brown  Southeast             0     28        Black   
18     52        Brown  Southeast             0     21        Blond   
19     52        Brown  Southeast             0     23        Brown   

    Validation_y  
0              1  
1              1  
2              0  
3              1  
4              1  
5              0  
6              1  
7              1  
8              0  
9              1  
10             1  
11             0  
12             0  
13             0  
14             0  
15             0  
16             0  
17             1  
18             1  
19             1

In [41]:
# left_merge

left_merge = df1.merge(df, on = 'US Region', how = 'left')
left_merge

Age_x Hair Color_x  US Region  Validation_x  Age_y Hair Color_y  \
0      21        Blond  Southwest             1     25        Black   
1      21        Blond  Southwest             1     35        Blond   
2      21        Blond  Southwest             1     33        Brown   
3      21        Blond  Southwest             1     25        Black   
4      24        Blond  Northeast             0     45          Red   
5      24        Blond  Northeast             0     35        Brown   
6      48        Black  Southwest             1     25        Black   
7      48        Black  Southwest             1     35        Blond   
8      48        Black  Southwest             1     33        Brown   
9      48        Black  Southwest             1     25        Black   
10     22        Black  Southwest             0     25        Black   
11     22        Black  Southwest             0     35        Blond   
12     22        Black  Southwest             0     33        Brown   
13     22        Black  Southwest             0     25        Black   
14     27        Brown  Northeast             0     45          Red   
15     27        Brown  Northeast             0     35        Brown   
16     28        Black  Southeast             1     52        Brown   
17     21        Blond  Southeast             1     52        Brown   
18     51        Black  Northwest             0     30        Black   
19     23        Brown  Southeast             1     52        Brown   

    Validation_y  
0              1  
1              0  
2              0  
3              0  
4              1  
5              0  
6              1  
7              0  
8              0  
9              0  
10             1  
11             0  
12             0  
13             0  
14             1  
15             0  
16             0  
17             0  
18             1  
19             0

In [42]:
# Right_merge
right_merge = df.merge(df1, on = 'US Region', how = 'right')
right_merge

Age_x Hair Color_x  US Region  Validation_x  Age_y Hair Color_y  \
0      25        Black  Southwest             1     21        Blond   
1      35        Blond  Southwest             0     21        Blond   
2      33        Brown  Southwest             0     21        Blond   
3      25        Black  Southwest             0     21        Blond   
4      45          Red  Northeast             1     24        Blond   
5      35        Brown  Northeast             0     24        Blond   
6      25        Black  Southwest             1     48        Black   
7      35        Blond  Southwest             0     48        Black   
8      33        Brown  Southwest             0     48        Black   
9      25        Black  Southwest             0     48        Black   
10     25        Black  Southwest             1     22        Black   
11     35        Blond  Southwest             0     22        Black   
12     33        Brown  Southwest             0     22        Black   
13     25        Black  Southwest             0     22        Black   
14     45          Red  Northeast             1     27        Brown   
15     35        Brown  Northeast             0     27        Brown   
16     52        Brown  Southeast             0     28        Black   
17     52        Brown  Southeast             0     21        Blond   
18     30        Black  Northwest             1     51        Black   
19     52        Brown  Southeast             0     23        Brown   

    Validation_y  
0              1  
1              1  
2              1  
3              1  
4              0  
5              0  
6              1  
7              1  
8              1  
9              1  
10             0  
11             0  
12             0  
13             0  
14             0  
15             0  
16             1  
17             1  
18             0  
19             1

### 15.	Split the below table and perform concat row wise and column wise



In [44]:
df

Age Hair Color  US Region  Validation
0   25      Black  Southwest           1
1   30      Black  Northwest           1
2   45        Red  Northeast           1
3   35      Blond  Southwest           0
4   33      Brown  Southwest           0
5   35      Brown  Northeast           0
6   25      Black  Southwest           0
7   52      Brown  Southeast           0

In [45]:
df1

Age Hair Color  US Region  Validation
8    21      Blond  Southwest           1
9    24      Blond  Northeast           0
10   48      Black  Southwest           1
11   22      Black  Southwest           0
12   27      Brown  Northeast           0
13   28      Black  Southeast           1
14   21      Blond  Southeast           1
15   51      Black  Northwest           0
16   23      Brown  Southeast           1

In [50]:
df3 = pd.concat([df, df1], axis = 0)
df3

Age Hair Color  US Region  Validation
0    25      Black  Southwest           1
1    30      Black  Northwest           1
2    45        Red  Northeast           1
3    35      Blond  Southwest           0
4    33      Brown  Southwest           0
5    35      Brown  Northeast           0
6    25      Black  Southwest           0
7    52      Brown  Southeast           0
8    21      Blond  Southwest           1
9    24      Blond  Northeast           0
10   48      Black  Southwest           1
11   22      Black  Southwest           0
12   27      Brown  Northeast           0
13   28      Black  Southeast           1
14   21      Blond  Southeast           1
15   51      Black  Northwest           0
16   23      Brown  Southeast           1

In [52]:
df4 = pd.concat([df, df1], axis = 1)
df4

Age Hair Color  US Region  Validation   Age Hair Color  US Region  \
0   25.0      Black  Southwest         1.0   NaN        NaN        NaN   
1   30.0      Black  Northwest         1.0   NaN        NaN        NaN   
2   45.0        Red  Northeast         1.0   NaN        NaN        NaN   
3   35.0      Blond  Southwest         0.0   NaN        NaN        NaN   
4   33.0      Brown  Southwest         0.0   NaN        NaN        NaN   
5   35.0      Brown  Northeast         0.0   NaN        NaN        NaN   
6   25.0      Black  Southwest         0.0   NaN        NaN        NaN   
7   52.0      Brown  Southeast         0.0   NaN        NaN        NaN   
8    NaN        NaN        NaN         NaN  21.0      Blond  Southwest   
9    NaN        NaN        NaN         NaN  24.0      Blond  Northeast   
10   NaN        NaN        NaN         NaN  48.0      Black  Southwest   
11   NaN        NaN        NaN         NaN  22.0      Black  Southwest   
12   NaN        NaN        NaN         NaN  27.0      Brown  Northeast   
13   NaN        NaN        NaN         NaN  28.0      Black  Southeast   
14   NaN        NaN        NaN         NaN  21.0      Blond  Southeast   
15   NaN        NaN        NaN         NaN  51.0      Black  Northwest   
16   NaN        NaN        NaN         NaN  23.0      Brown  Southeast   

    Validation  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN  
5          NaN  
6          NaN  
7          NaN  
8          1.0  
9          0.0  
10         1.0  
11         0.0  
12         0.0  
13         1.0  
14         1.0  
15         0.0  
16         1.0